### ISSUE TITLE
Just building tasks?

### ISSUE THREAD

**Issue by hannobraun** [neonphog/cargo-task#7]
I'd like to include the tasks in our repository in the CI build, but due to the magic `cargo_task_util` module, I can't just build the task crate.

Would it make sense to have a `cargo task build` command, that builds all tasks, but doesn't run them? Possibly with an optional argument, to build a specific task.

**Comment by neonphog** [comment]
@hannobraun - Or potentially there could be a flag that causes the cargo_task_util.rs to be generated into the task crate so you could commit it / run it?

**Comment by neonphog** [comment]
or as a separate cargo_task_util crate that would be referenced via path in the tasks' Cargo.tomls

**Comment by hannobraun** [comment]
> or as a separate cargo_task_util crate that would be referenced via path in the tasks' Cargo.tomls

I like this solution. It's less magical than the current situation (basically, the task would become a normal crate), and doesn't require that I manage a generated file in the repository.

And thank you for your for work on cargo-task, @neonphog! We've just started using it in [Step/Dir](https://github.com/braun-embedded/step-dir), and it seems to fill a need I've been having for a long time!

**Comment by neonphog** [comment]
@hannobraun 

[0.0.11 published to crates.io](https://crates.io/crates/cargo-task/0.0.11) including PR #9

You should be able to:

- `cargo install -f cargo-task` - to get the latest version
- `cargo task ct-init` - to cause the new `cargo_task_util` crate to be generated into your `.cargo-task` directory

You can either commit this to your version control, or ignore it depending on what works best for your workflow.

Thanks for the feedback!

**Comment by hannobraun** [comment]
That looks awesome. Thank you, @neonphog!

**Comment by hannobraun** [comment]
Hey @neonphog, I finally upgraded to the new version yesterday (got a bit sidetracked by my end-of-year vacation). Thanks again!

One idea for a possible improvement: What do you think about publishing `cargo_task_util` on crates.io? As it is now, I either commit the crate to my repository, or I need to run `cargo task ct-init` on every fresh clone (I've chosen the latter). Not a big deal, but if `cargo_task_util` was on crates.io, things would be even simpler.

The disadvantage would be, that you might get a mismatch between the installed `cargo-task` and the `cargo_task_util` dependency. I don't know how severe this would be in practice, but it would be possible for `cargo-task` to detect this mismatch and give an informative "your task needs an update" message, if that ever becomes a serious problem.

**Comment by neonphog** [comment]
@hannobraun 

> What do you think about publishing cargo_task_util on crates.io?

I did consider this, and indeed think it could be a good idea. I think we could pin the exact crates.io version via Cargo.toml

```
cargo_task_util = "=x.x.x"
```

(note the extra `=`)

My reason for not doing this is a little vain. I really like the idea of cargo-task having zero dependencies - so many of the other rust utilities like this have so many dependencies that it puts a real time burden on CI systems when installing them. While a single dependency will not make that much difference, it's much less impact-full to say 'only a single dependency' : )

**Comment by hannobraun** [comment]
Ha, I get it, but seeing this purely from the perspective of a user, I disagree :slightly_smiling_face: 

Some observations:
- "No dependencies" would still be true. The task runner still wouldn't have any dependencies, and the `cargo-task-util` dependency would be optional anyway, right? We're using ours only for logging.
- I don't think the "no dependencies" would be any less sincere, if there's an optional dependency that tasks can add to get additional capabilities (not sure what else is there, besides logging).
- Especially since that dependency is already there, as a local one (and was even there before, only hidden from Cargo).

As I said, this isn't a big deal, but I do think it would be slightly better. Having to remember and/or document that developers need to run a special initialization command before being able to use the tasks is also overhead, just of a different kind.

**Comment by neonphog** [comment]
@hannobraun - thanks for the feedback, you make some good points! I've created issue #10 to experiment with that when I get a moment, or, of course, feel free to submit a Pull Request : )

**Comment by hannobraun** [comment]
@neonphog To be honest, I'm quite busy with other open source work, so I'm hoping to benefit from some good old "maintainer doing work for free" type deal here :smile: 

I'll try to keep it in mind. Maybe I'll find a free spot to do it, but I wouldn't hold my breath.
